# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mfortuna <mfortuna@student.42porto.com>    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/03/18 11:04:58 by mfortuna          #+#    #+#              #
#    Updated: 2025/03/18 13:33:58 by mfortuna         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	: megafone
#CPP		: c++
CPPFLG	: -Wall -Wextra -Werror -std=c++98



all : $(NAME)

$(NAME) :
	c++ $(CPPFLG) megafone.cpp -o $(Name)
